### PR TITLE
Reformating most of the commands, added EmbedBuilder with most used c…

### PR DESCRIPTION
**Pull request by CakeAndBanana**
This will reduce size in the code in every module by removing unused codes and duplicates. Most stopwatches and loggers  are removed and one stopwatch and logger is added in the CommandHandler. I have created a EmbedBuilder to implement easy way to remember colors. Haven't tested anything yet, please test.

### CODE REVIEW

**Review by hburn7 — CHANGES_REQUESTED** [review]
In StaticMusicEmbeds.cs, please revert 
`public static async Task<Discord.Embed>`
to
`public static async Task<Embed>`

This change wasn't needed because Embeds are from Discord already.

**Comment by CakeAndBanana** [comment]
> In StaticMusicEmbeds.cs, please revert
> `public static async Task<Discord.Embed>`
> to
> `public static async Task<Embed>`
> 
> This change wasn't needed because Embeds are from Discord already.

Trying to change that will create a error that wouldn't be fixed with restarting or clean/rebuild the solution. This would have been the only way to fix it for me

**Comment by hburn7** [comment]
> > In StaticMusicEmbeds.cs, please revert
> > `public static async Task<Discord.Embed>`
> > to
> > `public static async Task<Embed>`
> > This change wasn't needed because Embeds are from Discord already.
> 
> Trying to change that will create a error that wouldn't be fixed with restarting or clean/rebuild the solution. This would have been the only way to fix it for me

That's fine then, no problem. Please also ensure that all successful command responses (apart from music commands) are with a Pink embed. (EXP command for example embeds with red instead of pink). `$osu` and `$osutop` commands do embed with pink, however, so I assume this would be a very simple fix.

I couldn't find any commands other than exp with the red embed, but please make sure that most other commands that should be embedded with a pink color are pink.

**Comment by hburn7** [comment]
Changes in this PR have been applied to #50. Thank you!

**Pull request closed without merging**
